---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Addon
metadata:
  generation: 1
  name: analyzer
  namespace: konveyor-tackle
spec:
  container:
    image: quay.io/konveyor/tackle2-addon-analyzer
    imagePullPolicy: Always
    name: addon
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
  task: ^(analyzer|tech-discovery)$
status:
  conditions:
  - lastTransitionTime: "2026-02-07T16:36:36Z"
    message: ""
    observedGeneration: 1
    reason: Validated
    status: "True"
    type: Ready
  observedGeneration: 1

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Addon
metadata:
  generation: 1
  name: language-discovery
  namespace: konveyor-tackle
spec:
  container:
    image: quay.io/konveyor/tackle2-addon-discovery:latest
    imagePullPolicy: Always
    name: addon
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  task: language-discovery
status:
  conditions:
    - lastTransitionTime: "2026-02-07T16:36:36Z"
      message: ""
      observedGeneration: 1
      reason: Validated
      status: "True"
      type: Ready
  observedGeneration: 1

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Addon
metadata:
  generation: 1
  name: platform
  namespace: konveyor-tackle
spec:
  container:
    image: quay.io/konveyor/tackle2-addon-platform:latest
    imagePullPolicy: Always
    name: addon
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "1"
        memory: 100Mi
  task: ^(application-import|application-manifest|asset-generation)$
status:
  conditions:
    - lastTransitionTime: "2026-02-07T16:36:36Z"
      message: ""
      observedGeneration: 1
      reason: Validated
      status: "True"
      type: Ready
  observedGeneration: 1
