---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: analyzer
  namespace: konveyor-tackle
spec:
  dependencies:
    - language-discovery
  priority: 10

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: application-import
  namespace: konveyor-tackle
spec:
  data:
    action: import

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: application-manifest
  namespace: konveyor-tackle
spec:
  data:
    action: fetch

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: asset-generation
  namespace: konveyor-tackle
spec:
  data:
    action: generate

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: language-discovery
  namespace: konveyor-tackle
spec:
  data:
    source: language-discovery

---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Task
metadata:
  name: tech-discovery
  namespace: konveyor-tackle
spec:
  data:
    mode:
      discovery: true
      withDeps: true
    rules:
      labels:
        included:
          - discovery
    tagger:
      enabled: true
      source: tech-discovery
  dependencies:
    - language-discovery
  priority: 1